version: "3.5"
services:
  chistera:
    build: .
    volumes:
      - "./:/opt/app"
    environment:
      - CONFIG_FILE=/run/secrets/config
    secrets:
      - config
  db:
    container_name: chistera-db
    image: mysql:5.7
    ports:
         - "3306:3306"
    environment:
        MYSQL_DATABASE: 'chistera'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
secrets:
  config:
    file: ./config.yaml